name: demo
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  demo_firebase_tools_install_hang:
    runs-on: ubuntu-latest
    steps:
      - name: Install Firebase CLI
        run: |
          curl -sL firebase.tools | bash
